### ISSUE TITLE
Clarification with preload spec?

### ISSUE THREAD

**Issue by ashumeow** [w3c/preload#1]
The definition of <a href="https://w3c.github.io/preload/#dfn-preload">pre-load</a> sounded a lot <a href="https://github.com/igrigorik/resource-hints/issues/3">similar</a> to <a href="https://docs.google.com/presentation/d/18zlAdKAxnc51y_kj-6sWLmnjl6TLnaru_WH0LJTjP-o/present?slide=id.gc03305a_0106">pre-fetch</a>. Is pre-load and pre-fetch are same? If not, Could you highlight me the differences between the both terms?

**Comment by igrigorik** [comment]
Preload has mandatory semantics: the user agent MUST fetch the specified resource. Prefetch is a speculative fetch (the user agent MAY fetch the specified resources) and is now defined as `<link rel=reload load-settings=next href=...>` in the Resource Hints spec -- see that for details.

**Comment by ashumeow** [comment]
Thanks!
