### ISSUE TITLE
Matching preload with different crossorigin attribute

### ISSUE THREAD

**Issue by yutakahirano** [w3c/preload#100]
Hi,

There is a note in the spec

> NOTE
> Preload links for CORS enabled resources, such as fonts or images with a crossorigin attribute, must also include a crossorigin attribute, in order for the resource to be properly used.

, but I'm not sure if the UA should match a preload without crosorigin attribute with a {mode: "cors"} request. I can interpret the note in two ways:

1. The UA should match the preload with the request, but the result may not be useful.
2. The UA should not match the preload with the request.

Chrome takes the second position for most of the cases (see [the code](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/loader/fetch/ResourceLoaderOptions.h?dr=CSs&q=ResourceLoaderOptions::CanReuseRequest+package:%5Echromium$&l=101)) but takes the first position for some cases (as=fetch, for example). Which is correct from the spec POV?

@yoavweiss @tyoshino

**Comment by yutakahirano** [comment]
I like the second option more because it is less confusing. When we choose the first option, it is possible to get a opaque-filtered response when you issue a fetch with mode: "cors", which is super-confusing.

**Comment by yutakahirano** [comment]
@annevk

**Comment by yutakahirano** [comment]
ping

**Comment by yoavweiss** [comment]
I like the second option, and if you see the first in implementations, I'm not sure that's not an issue. Do you have an example where that happens?

**Comment by yutakahirano** [comment]
If we choose the second option, I think we should attach "crossorigin" for all as=fetch preloads in spec examples. XHR's mode is always "cors" and I believe mode="cors" fetch is more common than mode="no-cors".

As you know, [Chrome currently doesn't support crossorigin XHR preloads](https://bugs.chromium.org/p/chromium/issues/detail?id=702845). Choosing the second option means Chrome is wrongly matching preloads with XHR requests and the feature should be disabled until [the issue](https://bugs.chromium.org/p/chromium/issues/detail?id=702845) is solved.

**Comment by yoavweiss** [comment]
Probably not the right forum for this, but I'd support disabling preload for `as=fetch` in Chromium until all underlying issues are resolved.

**Comment by yutakahirano** [comment]
How about spec examples? Are you fine with adding crossorigin attribute?

**Comment by yoavweiss** [comment]
Yes, I'd support that. I'd be happy to review a PR for that, or create one myself. Your call :)

**Comment by yutakahirano** [comment]
Thanks, I created https://github.com/w3c/preload/pull/102.
