### ISSUE TITLE
serviceworkers?

### ISSUE THREAD

**Issue by getify** [w3c/preload#11]
How do preload requests interact with service workers? That is, do they go through the service worker (which can interfere), or do they go directly out?

**Comment by igrigorik** [comment]
All fetches are routed through SW (as specced), preload is no exception.

**Comment by getify** [comment]
Does the SW know that the request is a special preload and not the real request?

Side note (slightly off topic): do SW's also intercept CORS preflight requests?

**Comment by igrigorik** [comment]
> Does the SW know that the request is a special preload and not the real request?

Yes, fetch has "context": https://fetch.spec.whatwg.org/#concept-request-context - we'd need to add "preload" as a value on that list. /cc @annevk

> Side note (slightly off topic): do SW's also intercept CORS preflight requests?

I believe it's skipped, see: https://fetch.spec.whatwg.org/#skip-service-worker-flag

**Comment by getify** [comment]
Thanks.
