### ISSUE TITLE
Privacy and security questionnaire self-assesment

### ISSUE THREAD

**Issue by yoavweiss** [w3c/preload#111]
As part of the TAG review process, I have read the [Privacy and Security Questionnaire](https://www.w3.org/TR/security-privacy-questionnaire/).
There are a couple of questions there which seemed relevant for preload:
* "Does this specification enable new script execution/loading mechanisms?"
    * preload does enable a new mechanism for script loading.
    * I believe that since it doesn't enable execution of said scripts without other script execution mechanisms (e.g. `<script>` tag), this does not expose any new attack vectors.
* "Does this specification deal with high-value data?"
    * preload does not deal with high profile data, but could have been used as a data exfiltration mechanism for such data. However, the fact that it's bound to the same CSP directives as the resource that it is loading (indicated by the `as` attribute) means that it doesn't enable data exfiltration more than any other resource loading tag.

I open this issue mainly as part of the TAG review. Following the review, we'll see if any of the above should be added to the "Security and Privacy Considerations" section.

**Comment by siusin** [comment]
TAG review done.

No feedback from the WebSec IG.
