### ISSUE TITLE
Performance impact?

### ISSUE THREAD

**Issue by edent** [w3c/preload#112]
> Fetching resources with XMLHttpRequest to avoid above behavior incurs a serious performance penalty 

Can you quantify the performance penalty? How much faster is using preload?

**Comment by yoavweiss** [comment]
As this is highly variable and depends on the page structure, network, user device and UA defined behavior, I don't think quantifying the performance advantage of preload should be part of the spec.

You can see external blog posts (such as @addyosmani's [article](https://medium.com/reloading/preload-prefetch-and-priorities-in-chrome-776165961bbf#0106)) or research papers (such as [VROOM](http://web.eecs.umich.edu/~harshavm/papers/vroom_sigcomm17.pdf)) for more details on said performance benefits.

**Comment by edent** [comment]
I strongly suggest that that pointing to those papers would be useful. At the moment, there's no quantifiable reason - or evidence - to suggest that preload will be useful to developers.

**Comment by addyosmani** [comment]
I have other data points around the efficacy of preload as a performance
primitive I could PR in or add to the original post. I'll defer to Your for
what he thinks makes the most sense here. Linking to the existing two
sources from his comment may be sufficient.

**Comment by yoavweiss** [comment]
Paging Dr. @igrigorik for his opinion here - should we link from the spec to external resources which prove the feature's benefits?

**Comment by igrigorik** [comment]
I believe we already provide the necessary context and motivation in the paragraphs above the quoted statement: 

> However, there are also cases where some resources need to be fetched as early as possible, but their processing and execution logic is subject to application-specific requirements - e.g. dependency management, conditional loading, ordering guarantees, and so on. Currently, it is not possible to deliver this behavior without a performance penalty.
>
> - Declaring a resource via one of the existing elements (e.g. img, script, link) couples resource fetching and execution. Whereas, an application may want to fetch, but delay execution of the resource until some condition is met.
> - Fetching resources with XMLHttpRequest to avoid above behavior incurs a serious performance penalty by hiding resource declarations from the user agent's DOM and preload parsers. The resource fetches are only dispatched when the relevant JavaScript is executed, which due to abundance of blocking scripts on most pages introduces significant delays and affects application performance.

With respect to "preload use in the wild", I don't believe the spec is the right place to enumerate or maintain such a list — that's what developer documentation (e.g. MDN) resources are for.
