### ISSUE TITLE
RFC 5988 was silently obsoleted by RFC 8288

### ISSUE THREAD

**Issue by mdocguard** [w3c/preload#119]
RFC 8288 (Oct 2017) says that it obsoletes 5988, but RFC 5988 doesn't say anything about its obsoleteness by 8288. While this is clearly an IETF issue, I thought it's better that this TR be updated with a newer RFC.

**Comment by yoavweiss** [comment]
As the draft is discontinued, I think we can close this. The [processing of this](https://html.spec.whatwg.org/multipage/semantics.html#processing-link-headers) is now integrated into HTML, and doesn't mention any of these RFCs.
