### ISSUE TITLE
cross-realm?

### ISSUE THREAD

**Issue by getify** [w3c/preload#12]
If I "preload" a resource in a parent page then make the "matching" request in an iframe, or otherwise in some other realm (web workers, etc), does it all match up? Or is this only per realm?

**Comment by igrigorik** [comment]
Subject to regular HTTP caching semantics -- max-age, etc. For resources that are "no-cache" the resource is only retained within that navigation context. 

Once again, dupe of https://github.com/w3c/resource-hints/issues/2 - let's continue there.
