### ISSUE TITLE
spec should mention that relList must also be implemented if preload is implemented

### ISSUE THREAD

**Issue by safareli** [w3c/preload#126]
creating this issue out of the last comments from https://github.com/w3c/preload/issues/7#issuecomment-400462295

**Comment by noamr** [comment]
I don't know if this needs to be actionable now that preload is merged into HTML. Can we close this @yoavweiss?

**Comment by yoavweiss** [comment]
Maybe we should add an implementer note to `<link>` indicating that the feature detection for the various `rel` values is done through `relList`?

**Comment by noamr** [comment]
> Maybe we should add an implementer note to `<link>` indicating that the feature detection for the various `rel` values is done through `relList`?

I think that would be redundant. Won't we have to add that note in all 15 or so mentions of `rellist`? The definition of [reflect](https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#reflect) already specifies that `rellist` parses the attribute for [known values](https://html.spec.whatwg.org/multipage/common-dom-interfaces.html#limited-to-only-known-values).

**Comment by yoavweiss** [comment]
What I was thinking is just add a single note at the end of [the link element](https://html.spec.whatwg.org/multipage/semantics.html#the-link-element) section, indicating that `relList` is used by developers for feature detection, in order to address the OP's complaint that there's no mention of `relList` here.

At the same time, if you or the HTML editors don't think it makes sense to do that, I can definitely accept that.

/cc @domenic for thoughts on this

**Comment by noamr** [comment]
> What I was thinking is just add a single note at the end of [the link element](https://html.spec.whatwg.org/multipage/semantics.html#the-link-element) section, indicating that `relList` is used by developers for feature detection, in order to address the OP's complaint that there's no mention of `relList` here.
> 
> At the same time, if you or the HTML editors don't think it makes sense to do that, I can definitely accept that.
> 
> /cc @domenic for thoughts on this

I guess an editorial note doesn't hurt, see https://github.com/whatwg/html/pull/7756

**Comment by yoavweiss** [comment]
That's exactly what I had in mind, thanks!! :)
