### ISSUE TITLE
Preloads triggered by speculative fetches should be speculative

### ISSUE THREAD

**Issue by yoavweiss** [w3c/preload#129]
Preload is defined as a mandatory fetch, but it is possible that preload Link headers are delivered over speculative fetches (e.g. prefetch).

We should exempt such preloads from being mandatory and make them speculative, similar to the vector on which the links arrived.

**Comment by toddreifsteck** [comment]
Discussed at TPAC 2018:
* Apple made it clear that all networking is a suggestion as User Agents are implemented today
* HTML mechanisms that provoke fetch result in this being undetectable
* Given that script/CSS don't metion this, it may not be a blocking issue to note that preload may not occur
* If we want to specify, we may want to specify this as a part of specifying "speculative download" on prefetch or specifically on fetch

**Comment by noamr** [comment]
I think this is true for every fetch and not specific to preload. Can we close this @yoavweiss?

**Comment by yoavweiss** [comment]
While I don't think this is true in the prefetch case (prefetches can't trigger resource loading before being consumed), it is true for the prerendering case. If this is covered elsewhere in a more generic sense, I'm cool with closing this.

**Comment by noamr** [comment]
Closing, this issue belongs in https://github.com/WICG/nav-speculation/
