### ISSUE TITLE
Question: What is the correct way to create ranges for media attributes?

### ISSUE THREAD

**Issue by ghost** [w3c/preload#132]
Sorry to have to post this question, but I can't find the solution in the [spec](https://w3c.github.io/preload/) and also in other documentation like on [mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content) and the [smashing magazine](https://www.smashingmagazine.com/2016/02/preload-what-is-it-good-for/) etc.

I understand to add the media attribute for the image you can write the following code:

`<link rel="preload" href="example.png" as="image" media="(max-width: 650px)">`

My question is what would be the correct code syntax for giving the same image a range let's say of `320px - 650px` for example:

`@media screen and (min-width: 320px) and (max-width: 650px)`

So my guess would be something like this:

`<link rel="preload" href="example.png" as="image" media="(min-width: 320px) and (max-width: 650px)>`

I just want to know if that is the correct syntax for the preload.

Also an extra question can I use `rem` instead of `px` e.g.

`<link rel="preload" href="example.png" as="image" media="(min-width: 20rem) and (max-width: 40.63rem)>`

I hope someone can answer this question and also add this to the spec to help other people.

**Comment by domfarolino** [comment]
> So my guess would be something like this:

Your example looks good to me. The value within a `media` attr can be a media query, so examples of that may be better off in MDN or something of the sort. RE `rem` in media query, I am not 100% sure.

For reference see resources like:
 - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#Attributes
 - https://www.sitepoint.com/community/t/range-of-the-css-media-query/258659/2

**Comment by ghost** [comment]
Thanks for the reply and links! I will keep researching this and try to find out, hopefully some more comments can come and some extra info in the spec.

**Comment by yoavweiss** [comment]
Thanks @domfarolino for answering!
