### ISSUE TITLE
Preload fonts and font-display: swap do not work together

### ISSUE THREAD

**Issue by ghost** [w3c/preload#133]
I noticed this issue this week and I thought I'd mention it. Tested in Google Chrome Version 72.0.3613.0

If you do the following code (it will work):

```
@font-face {
  font-family: 'Noto Sans';
  font-style: normal;
  font-weight: 400;
  src: local('Noto Sans'), local('NotoSans'),
       url('/assets/fonts/noto-sans-v7/noto-sans-v7-latin-regular.woff2') format('woff2'),
       url('/assets/fonts/noto-sans-v7/noto-sans-v7-latin-regular.woff') format('woff');
}

<link rel="preload" href="/assets/fonts/noto-sans-v7/noto-sans-v7-latin-regular.woff2" as="font" type="font/woff2" crossorigin="anonymous">
```

If you add the `font-display: swap` (it will not work):

```
@font-face {
  font-family: 'Noto Sans';
  font-style: normal;
  font-weight: 400;
  font-display: swap; 
  src: local('Noto Sans'), local('NotoSans'),
       url('/assets/fonts/noto-sans-v7/noto-sans-v7-latin-regular.woff2') format('woff2'),
       url('/assets/fonts/noto-sans-v7/noto-sans-v7-latin-regular.woff) format('woff');
}

<link rel="preload" href="/assets/fonts/noto-sans-v7/noto-sans-v7-latin-regular.woff2" as="font" type="font/woff2" crossorigin="anonymous">
```

The following error will show in dev-tools:

![untitled](https://user-images.githubusercontent.com/17784082/48660918-c1dccb00-ea61-11e8-82f0-2c6a159b49d5.png)

I was kind of expecting the browser to preload the font and 'hang on to it' while it goes through the swapping stage.

**Comment by igrigorik** [comment]
@ayumihamsaki thanks for reporting this. This looks like an implementation issue, not a spec issue. Could you please open a bug on crbug.com with same description and CC @yoavweiss and myself on the bug?

**Comment by ghost** [comment]
@igrigorik not sure how to cc you both, please see the opened issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=906364

**Comment by igrigorik** [comment]
Great, thank you! Closing this, let's continue on crbug :-)
