### ISSUE TITLE
Conflicting Link and <link>

### ISSUE THREAD

**Issue by karlcow** [w3c/preload#135]
What is supposed to happen when at the HTTP level, we have

`Link: </css/shiny.css>; as=style; rel=preload`

and the HTML document has:

```html
<link href="/css/shiny.css" type="text/css" rel="stylesheet">
```

* Checking [RFC8288](https://tools.ietf.org/html/rfc8288#appendix-A.1) which obsoleted RFC5988, not clarifying the processing order.
*  And [HTML is not clear either ](https://html.spec.whatwg.org/multipage/semantics.html#processing-link-headers) about possible conflicts.
* yoohoo there is another spec talking about it [CSSOM](https://drafts.csswg.org/cssom/#requirements-on-user-agents-implementing-the-http-link-header) but still no clues.

**Comment by domfarolino** [comment]
https://github.com/whatwg/html/issues/4224 discusses making it clear (in the HTML Standard) that the semantics of `Link:` and `<link>` are the same, so assuming that pans out, I think ultimately having both:

```
Link: </css/shiny.css>; as=style; rel=preload
<link href="/css/shiny.css" type="text/css" rel="stylesheet">
```

...per spec, someday, will be the same "conflict" as:

```
<link href="/css/shiny.css" type="text/css" rel="stylesheet">
<link href="/css/shiny.css" type="text/css" rel="stylesheet">
```

...in your document, which I don't think is unspecified.

**Comment by karlcow** [comment]
@domfarolino I guess you meant

```html
<link href="/css/shiny.css" as="style" rel="preload">
<link href="/css/shiny.css" type="text/css" rel="stylesheet">
```

**Comment by domfarolino** [comment]
Ah, yeah I kinda botched that. Thanks; point remains.

**Comment by yoavweiss** [comment]
I agree with @domfarolino's analysis. Closing this as this is not actionable.
