### ISSUE TITLE
Inconsistent load order behavior (Chrome)

### ISSUE THREAD

**Issue by iamskok** [w3c/preload#146]
I'm experimenting with dynamically adding `<link rel="preload">` tag for loading font files based on the user connection `navigator.connection.effectiveType`, e.g. if effective type is '4g' inject  `<link as="font" type="font/woff2" rel="preload" crossorigin="anonymous" href="inter-var.woff2">` in the `head` tag before any other resources, if connection is 'slow-2g' / '2g' / '3g' don't inject `link`. 

I'm also loading other resources using `preload`, but they are not as critical as fonts thus they are injected after the font files.

```
<head>
  // some other code
  <script id="connection-type-checker">
    (() => {
      const inter = document.createElement('link')
      const interItalic = document.createElement('link')
      const firaCode = document.createElement('link')

      inter.as = 'font'
      inter.type = 'font/woff2'
      inter.rel = 'preload'
      inter.crossOrigin = 'anonymous'
      inter.href = 'inter-var.woff2'

      interItalic.as = 'font'
      interItalic.type = 'font/woff2'
      interItalic.rel = 'preload'
      interItalic.crossOrigin = 'anonymous'
      interItalic.href = 'inter-var-italic.woff2'

      firaCode.as = 'font'
      firaCode.type = 'font/woff2'
      firaCode.rel = 'preload'
      firaCode.crossOrigin = 'anonymous'
      firaCode.href = 'fira-code.woff2'

      const insertAfter = (newNode, referenceNode) => referenceNode
        .parentNode.insertBefore(newNode, referenceNode.nextSibling)

      const target = document.getElementById('connection-type-checker')

      insertAfter(inter, target)
      insertAfter(interItalic, target)
      insertAfter(firaCode, target)
    })()
  </script>

  // **This is where <link>s get injected**

  // some other code...

  <link as="script" rel="preload" href="script.js" crossorigin="anonymous">
</head>
```

The problem I'm facing is that Chrome doesn't keep the original order for resources loaded with link preload if the `link` element was created with JavaScript (if link elements are inlined as HTML in the `head` tag everything works as expected).

 * [Example](https://github.com/iamskok/dynamic-link-preload-test)
 * [Repo](https://github.com/iamskok/dynamic-link-preload-test)

Screenshot:

 * Safari (respects the original order)
 * Chrome (doesn't respect the original order)
 * Firefox (doesn't support link preload)

[![Safari, Chrome, Firefox][1]][1]

  [1]: https://i.stack.imgur.com/YNyrr.jpg

I'm trying to understand why the original order is breaking in Chrome and if it can be fixed?

**Comment by domfarolino** [comment]
I've responded over at https://stackoverflow.com/questions/61419382/. I think it's probably best to close this bug and open a new on on https://crbug.com, since this is pretty much Chrome-specific, dealing with the preload scanner it seems.

**Comment by iamskok** [comment]
@domfarolino Thanks for the explanation in [StackOverflow]( https://stackoverflow.com/questions/61419382/). The bug was [reported](https://bugs.chromium.org/p/chromium/issues/detail?id=1074587) 🐛
