### ISSUE TITLE
"Delay the load event" should happen in HTML 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/preload#147]
As discussed in whatwg/html#5595 ... this spec talks about "MUST NOT delay the load event". However, that should be defined in the HTML spec, not in this spec.

**Comment by domfarolino** [comment]
I think this is already in the HTML Standard (https://html.spec.whatwg.org/multipage/semantics.html#fetching-and-processing-a-resource-from-a-link-element), so it seems we just need to delete things from this spec and we're finished. Is that right?

**Comment by marcoscaceres** [comment]
Yep, seems right. I didn’t realize it was already there.

**Comment by noamr** [comment]
preloads are integrated into HTML now, so perhaps this can proceed.

**Comment by noamr** [comment]
Nothing needs to be done here.
