### ISSUE TITLE
Link header processing

### ISSUE THREAD

**Issue by annevk** [w3c/preload#148]
Apparently the Link header (for preload) is not just processed when navigating, but also subresources (see https://bugzilla.mozilla.org/show_bug.cgi?id=1637653). Where is this defined?

**Comment by domfarolino** [comment]
What about other Link headers (non preload)? Are they to only be processed on navigations? Is that defined somewhere?

**Comment by yoavweiss** [comment]
I don't believe any of them are defined anywhere. They definitely should be...

**Comment by domfarolino** [comment]
https://html.spec.whatwg.org/multipage/semantics.html#processing-link-headers seems very vague

**Comment by yoavweiss** [comment]
After [discussion](https://docs.google.com/document/d/1fHD8Eqyt6vInbZu3vkIVhPVrRPtGpNmaQgzKppVW4xY/edit#bookmark=id.q9lp6ppn9car) at the WebPerfWG, we concluded that this processing would be better defined in HTML (as this is not preload specific).

**Comment by domfarolino** [comment]
Sounds like we should close this in favor of https://github.com/whatwg/html/issues/4224 ?

**Comment by yoavweiss** [comment]
SGTM!

**Comment by annevk** [comment]
Is it? What other relations are processed for subresources? If HTML were to define this I would expect it to process them when getting a response for a document that will be rendered in some fashion.

**Comment by yoavweiss** [comment]
That's a good point. Fetch might be a better place.

The other `rel` I had in mind is `preconnect`.

**Comment by andydavies** [comment]
I'd add `prefetch` too

Use case: 

3rd party widget e.g. chat, loads a minimal amount of code to add a FAB to the page, but uses `prefetch` in the response headers to fetch the rest of it's bundle inertly ready for when a user interacts

Of course it could do the same thing by inserting `link` elements into the DOM

**Comment by annevk** [comment]
Shall we keep this open until we have a better idea about the design and actions to take?

**Comment by yoavweiss** [comment]
Sure!
