### ISSUE TITLE
Link to or merge with HTML definition of "preload"

### ISSUE THREAD

**Issue by jyasskin** [w3c/preload#154]
It's confusing for both this document and https://html.spec.whatwg.org/multipage/links.html#link-type-preload to define pieces of the behavior of "preload" links. For example, in https://github.com/WICG/webpackage/pull/591#discussion_r469537152, I couldn't find the [linked resource fetch setup steps](https://html.spec.whatwg.org/multipage/semantics.html#linked-resource-fetch-setup-steps) for "preload" links because I looked in this document, but they're actually defined in HTML. I looked here because this document defines the "appropriate times" used by https://html.spec.whatwg.org/multipage/semantics.html#processing-the-type-attribute.

It could make sense for either all of the subroutines called by https://html.spec.whatwg.org/multipage/semantics.html to live here or in HTML, but they shouldn't be split between the specifications.

**Comment by yoavweiss** [comment]
@domenic thoughts?

**Comment by domenic** [comment]
In general we try to define the behavior of the link tag entirely in HTML, so the more we can move there, the better. That's what we recently did with rel=manifest, for example.

**Comment by plehegar** [comment]
(this has been placed on the list of WHATWG SG/W3C items to go through)

**Comment by noamr** [comment]
Can this be closed? preload is now defined in HTML
https://html.spec.whatwg.org/multipage/links.html#link-type-preload

**Comment by jyasskin** [comment]
There's probably something left to do in this spec, to remove the pieces that are now defined in HTML?

**Comment by jyasskin** [comment]
The [appropriate times](https://w3c.github.io/preload/#dfn-appropriate-times) to process the link should almost certainly move to HTML now that all the rest of the processing lives there. Otherwise it's very hard to find them by just reading https://html.spec.whatwg.org/multipage/links.html#link-type-preload.

**Comment by noamr** [comment]
I believe everything has moved to HTML, I'm not sure there's anything else left in this spec.
Not sure what's the appropriate wording to put here to direct users to the right place.
@yoavweiss?

**Comment by caribouW3** [comment]
We will probably republish the W3C document as Discontined Draft with explanantion in the status of the document.

**Comment by jyasskin** [comment]
Yeah, if truly everything has moved into HTML, and there's nothing left of value in this repo, I would delete the document's contents, add a "moved to HTML" paragraph that links to the appropriate places within HTML, either in the Status section or in a dedicated section, and then probably archive this repository.

**Comment by caribouW3** [comment]
Preload has been republished as DIscontinued draft, https://www.w3.org/TR/2022/DISC-preload-20220331/
