### ISSUE TITLE
Spec should more clearly when events should be fired at preload links.

### ISSUE THREAD

**Issue by emilio** [w3c/preload#155]
```html
<!doctype html>
<link href="https://crisal.io/tmp/foo.css" onerror="console.log('error', this.outerHTML)" onload="console.log('load', this.outerHTML)" as="style" rel="preload" media="print"> <!-- Non-matching media -->
<link href="https://crisal.io/tmp/foo.css" onerror="console.log('error', this.outerHTML)" onload="console.log('load', this.outerHTML)" as="style" rel="preload" type="text/html"> <!-- Invalid mime type -->
```

In both these cases, Firefox right now fires an `error` event, while other browsers don't. The spec doesn't quite say which implementation is correct. I'm fixing Firefox to do the same as other browsers, but this should be fixed regardless.

**Comment by noamr** [comment]
The HTML integration is complete now, and there is no mention of the `error` event.
https://html.spec.whatwg.org/multipage/links.html#link-type-preload

I think this can be closed, and we can reopen if we want to discuss adding error events to preload links.
