### ISSUE TITLE
Asynchronous fetch

### ISSUE THREAD

**Issue by yoavweiss** [w3c/preload#19]
Following yesterday's discussion during the call and @zcorpan's comment on #10, I think we should make it explicit in "The appropriate time to obtain..." paragraph that the loading itself should be done in an asynchronous manner. (using a microtask, etc)

The main benefits are consistency with the rest of the platform as well as not having to worry which attribute is modified first for cases where the loading is triggered by a multiple attribute mutation.

**Comment by igrigorik** [comment]
100% with you on consistency.. isn't this already covered by the html spec? 
- http://www.w3.org/TR/html5/document-metadata.html#concept-link-obtain
  - http://www.w3.org/TR/html5/infrastructure.html#potentially-cors-enabled-fetch
    - http://www.w3.org/TR/html5/webappapis.html#queue-a-task

I'd love to avoid having to define own processing sections, and instead link and reuse existing logic.

**Comment by yoavweiss** [comment]
The load event seems to be asynchronous, but not the fetch itself. (I used the term "loading" earlier, which is confusing)
Again, @zcorpan may know the right places to hook on :)

**Comment by igrigorik** [comment]
@zcorpan ping. any suggestions for how to make this behavior more clear in the spec?

**Comment by igrigorik** [comment]
@zcorpan @yoavweiss _bump_... any recommendations?

**Comment by yoavweiss** [comment]
I'll defer to @zcorpan. This is mainly a spec issue (i.e. I think we all agree that it should be async, it's just a matter of properly defining it).

**Comment by igrigorik** [comment]
Closing, should be resolved via #29.
