### ISSUE TITLE
more questions about load events

### ISSUE THREAD

**Issue by getify** [w3c/preload#20]
1. What happens if I attach a load handler after resource is already finished preloading? Does the event still fire?
2. What if I make multiple `<link rel=preload>` elements for the same resource, will all of them have the load event fired?

**Comment by igrigorik** [comment]
> What happens if I attach a load handler after resource is already finished preloading? Does the event still fire?

No, you missed the load event. Same behavior as other onload callbacks.

> What if I make multiple `<link rel=preload>`elements for the same resource, will all of them have the load event fired?

Yep, same as current behavior.. Simple example: http://jsbin.com/weturemehe/quiet
