### ISSUE TITLE
Whitelist for "as"

### ISSUE THREAD

**Issue by jakearchibald** [w3c/preload#21]
I don't think all of the values make sense for preload.
- `audio` - yep
- `beacon` - probably not?
- `cspreport` - probably not?
- `download` - yes
- `embed` - yep
- `eventsource` - yes
- `favicon` - yes
- `fetch` - yes
- `font` - yes
- `form` - yes
- `frame` - yes
- `hyperlink` - yes
- `iframe` - yes
- `image` - yes
- `imageset` - yes
- `import` - yes
- `internal` - no
- `location` - yes
- `manifest` - no
- `metarefresh` - no
- `object` - yes
- `ping` - no
- `plugin` - yes
- `prefetch` - no
- `preload` - no
- `prerender` - no
- `script` - yes
- `serviceworker` - hmm, this is a tricky one without the scope definition, so I'm going to say no
- `sharedworker` - yes
- `subresource` - no
- `style` - yes
- `track` - yes
- `video` - yes
- `worker` - yes
- `xmlhttprequest` - yes
- `xslt` - yes

**Comment by jakearchibald** [comment]
It may even make sense to group some of these. Eg, allow "page" instead of "download" or "hyperlink" or "location" or "form" etc etc. The prefetch spec already has `as=page`

**Comment by jakearchibald** [comment]
Actually, it has `as=html`, which is wrong I think. Since you can fetch html with `fetch()` or `<iframe>`, and the requests are different.

**Comment by igrigorik** [comment]
- beacon, ping: these are fine, there is no reason to exclude them, I think.
- manifest: why are you excluding it?

Grouping: it's an interesting idea, but I'm worried that it won't be granular enough to allow for appropriate headers and prioritization. I think I'd rather just map directly to Fetch.

Re, as=html: good catch, what would be the best option for this on the existing Fetch list?

**Comment by igrigorik** [comment]
Moving away from "as": https://github.com/whatwg/fetch/issues/64#issuecomment-115700995
