### ISSUE TITLE
Compatibility with rel="subresource"

### ISSUE THREAD

**Issue by adactio** [w3c/preload#23]
Does rel="preload" supercede the rel="subresource" proposal, or should the two potentially be used in combination e.g. rel="subresource preload"?

**Comment by igrigorik** [comment]
Subresource was never standardized and afaik was only ([and poorly](https://code.google.com/p/chromium/issues/detail?id=312327)) implemented in Chrome. Preload provides same and improved functionality.. so, it supersedes subresource.

**Comment by adactio** [comment]
Thanks for the clarification, Ilya.
