### ISSUE TITLE
Loading only after the <link> was added to the document?

### ISSUE THREAD

**Issue by yoavweiss** [w3c/preload#24]
From https://w3c.github.io/preload/#h-fetching-the-preload-link it is not clear if the resource download should start when the HTMLLinkElement was created, or only after it was added to the document.
From the implementation, I saw that `prefetch` and `subresource` were fetching only when in document, so I matched that, but we should be explicit about whether or not this is the right behavior, to avoid interoperability issues.

**Comment by igrigorik** [comment]
Hmm, it does indicate that it should apply when only/when "in a Document":

> When the preload link is created on a link element that is already _in a Document_.
> When the href attribute of the link element of an preload link that is already _in a Document_ is changed.

FWIW, this is same language as HTML spec uses for stylesheets.

**Comment by yoavweiss** [comment]
Fair enough. I'm missing a couple of scenarios here, which I see are [covered for stylesheets](https://html.spec.whatwg.org/multipage/semantics.html#link-type-stylesheet)

Can we add:

```
* When the preload link's link element is inserted into a document.
* When the crossorigin attribute of the link element of a preload link that is already in a Document is set, changed, or removed.
```

Also - not sure what `as` based mutations should do.

**Comment by igrigorik** [comment]
@yoavweiss added both of the above in acabd50. Re, "as" mutations: good question, and I think it'll depend on how we define it.. let's tackle that as part of that effort. Closing, feel free to reopen if there are other cases we haven't accounted for.
