### ISSUE TITLE
Remove `loadpolicy`

### ISSUE THREAD

**Issue by yoavweiss** [w3c/preload#25]
I think https://w3c.github.io/preload/#load-and-processing-policy is no longer relevant and can be removed (or at least significantly modified), since we added `prefetch` and `prerender` to Resource Hints. The equivalent parts in Resource Hints were removed.

**Comment by igrigorik** [comment]
Yup, that's what https://github.com/w3c/preload/pull/17 is for. Right now it's blocked due to "as" bit..

**Comment by yoavweiss** [comment]
Right. Missed it somehow...
