### ISSUE TITLE
Allowing an empty/invalid `as`?

### ISSUE THREAD

**Issue by yoavweiss** [w3c/preload#36]
@igrigorik - in a [comment](https://code.google.com/p/chromium/issues/detail?id=523036#c10) on a Blink issue, you mentioned that we allow empty `as` values, and we should treat them as low priority.

OTOH, you've argued the opposite when we [made `as` mandatory](https://github.com/w3c/preload/issues/2), and I agree with your arguments there, especially "it forces the developer to explicitly think through and declare how this resource should be treated".

Do you remember the reasoning for this change? Is there a particular reason to allow an empty `as`?

I believe that allowing it will result in a hard to detect foot-gun (e.g. setting its value to 'javascript' instead of 'script'), where if we disallow it, coupled with console logs, it would be easier to correct and detect.

**Comment by igrigorik** [comment]
The reason for the switch is because we redefined ["destination" in Fetch](https://fetch.spec.whatwg.org/#concept-request-destination) and we map `as` attribute value to `type`.. and `type` is allowed to be left empty.

A related question is what CSP policy we ought to be enforcing though given that `type` often maps to multiple possible CSP directives... And now that I think about it, it doesn't makes sense to pick a default, since a given default may not match your intended use (e.g. you can use `as=script` to fetch a worker script, but that should enforce `worker-src`, not `script-src`). As such, because CSP will be enforced by the consumer of the response (script tag, etc), I think we're back to where we were earlier.. namely, CSP is enforced by the consumer of the preload'ed response, not on preload itself.

/cc @mikewest for sanity check.

**Comment by igrigorik** [comment]
Oh, and for `javascript` vs `script`.. we can continue emitting console.logs for invalid `as` values. Empty value is valid, so it wouldn't / shouldn't emit any warnings.

**Comment by yoavweiss** [comment]
> The reason for the switch is because we redefined "destination" in Fetch and we map as attribute value to type.. and type is allowed to be left empty.

We still can avoid converting invalid values to the empty string, or even exclude the empty value when used in preload, if we believe it would be better for authors.

> Oh, and for javascript vs script.. we can continue emitting console.logs for invalid as values. Empty value is valid, so it wouldn't / shouldn't emit any warnings.

Yeah, console errors are definitely in order for invalid values.

> A related question is what CSP policy we ought to be enforcing though given that type often maps to multiple possible CSP directives... And now that I think about it, it doesn't makes sense to pick a default, since a given default may not match your intended use (e.g. you can use as=script to fetch a worker script, but that should enforce worker-src, not script-src). As such, because CSP will be enforced by the consumer of the response (script tag, etc), I think we're back to where we were earlier.. namely, CSP is enforced by the consumer of the preload'ed response, not on preload itself.

Is `script` the only type that maps to multiple directives? Can we perhaps split it into multiple types?

If not, what would be the CSP directive applicable for preloaded requests? `connect-src`?

**Comment by igrigorik** [comment]
> We still can avoid converting invalid values to the empty string, or even exclude the empty value when used in preload, if we believe it would be better for authors.

Agreed on invalid values, but don't think we can mark the empty value as such.. Unless we change Fetch spec to encompass more 'type' properties. 

> Is script the only type that maps to multiple directives? Can we perhaps split it into multiple types? If not, what would be the CSP directive applicable for preloaded requests? connect-src?

No, see the table here: https://fetch.spec.whatwg.org/#concept-request-destination. For background on how we arrived here: https://github.com/whatwg/fetch/issues/93#issuecomment-125289983.

**Comment by yoavweiss** [comment]
Regarding invalid values, during the 11/11/15 call, we reached a conclusion that we must accept invalid values and treat them as empty in order to be future compatible.

Regarding the type=>CSP context discussion, I'll open a separate issue

**Comment by yoavweiss** [comment]
Thinking about this some more, I want to reopen this issue.

Currently unsupported `as` values are omitted:
"Validate the request destination given by the as attribute. If the attribute is omitted, or the provided value is not a valid request destination, then initialize it to the empty string."

That can cause a situation where introducing browser support to a new destination value can result in double downloads in non-supporting browsers (which fetch the preload resource as an empty destination, which means it will not match any resource that is not an empty destination, e.g XHR).

I think that avoiding to preload unsupported destinations is a better option, assuming that browsers will also immediately fire the onerror handler, allowing web apps to cope with that lack of support.

@igrigorik - WDYT?

**Comment by igrigorik** [comment]
That seems reasonable to me. If the implementation does not support the destination type, we throw an error and the developer can fallback to some other means. In the case of a header, it would simply be a no-op (no download, but no callbacks either). 

@annevk can you sanity check?

**Comment by annevk** [comment]
I guess that's reasonable, @mikewest should really confirm since this is really about how CSP works. I used to think CSP had some kind of fallback semantics, so that if you are allowed to connect-src something you can also img-src it, but I guess it's mostly mutually exclusive, with some specific fallbacks.

**Comment by yoavweiss** [comment]
Since I'm suggesting to change behavior to avoid preloading of unknown `as` values (regardless of CSP), I don't think there would be any new CSP concerns here.
