### ISSUE TITLE
Register "preload" with IANA

### ISSUE THREAD

**Issue by dret** [w3c/preload#41]
seeing that http://www.iana.org/assignments/link-relations/link-relations.xhtml currently does not list "preload" as a registered link relation type, i am proposing to add a section to the draft that registers "preload" in the IANA registry according to RFC 5988. i'd be more than happy to contribute such a section. this should make it easier for people discovering "preload" links on the web to find the authoritative document specifying the link relation type.
(for an example of how this section might look like, please have a look at https://github.com/aaronpk/webmention/pull/30)

**Comment by igrigorik** [comment]
@dret I'd be happy to accept a PR :)

**Comment by dret** [comment]
On 2016-01-13 17:20, Ilya Grigorik wrote:

> @dret https://github.com/dret I'd be happy to accept a PR :)

sweet! stay tuned...

**Comment by dret** [comment]
https://github.com/w3c/preload/pull/42 is a first attempt, please feel free to improve the description. not sure whether what's there right now is the best way to explain "preload" in one or two sentences.

**Comment by plehegar** [comment]
https://mailarchive.ietf.org/arch/search/?email_list=link-relations&q=preload

**Comment by mnot** [comment]
Note that you don't _have_ to include the template in the spec; it's just a convenient way to get agreement on the form of the registration request.

**Comment by dret** [comment]
On 2016-01-17 19:46, Mark Nottingham wrote:

> Note that you don't /have/ to include the template in the spec; it's
> just a convenient way to get agreement on the form of the registration
> request.

true, thanks for the feedback. but it's a nice pattern to follow, and an 
easy way for people to spot what's being registered by a spec they are 
looking at. at least that's my way of looking at this lightweight and 
easy piece of formalism.

**Comment by dret** [comment]
http://mailarchive.ietf.org/arch/msg/link-relations/7323wsx0g0F4yVZ9PFuq59gze8A is the email asking for registration in the IANA link relation type registry.

**Comment by dret** [comment]
since https://github.com/w3c/preload/pull/42 has been merged, this issue probably can be closed.

**Comment by dret** [comment]
looks like we're in good shape: http://mailarchive.ietf.org/arch/msg/link-relations/uQLYaotW-KH1AS0nUfYbw1E_vMs
thanks, @mnot.

**Comment by igrigorik** [comment]
Great, thanks guys!

**Comment by dret** [comment]
sweet, IANA has added the link to the registry: http://www.iana.org/assignments/link-relations/link-relations.xhtml
