### ISSUE TITLE
should default loadPolicy have a name?

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/preload#5]
The specified default loadPolicy does not have a name. If I specify loadPolicy="<anyundefined", I assume it will get the default. Should we specify loadPolicy="default" as a reserved word for devs who like to be explicit?

**Comment by igrigorik** [comment]
This is similar to https://github.com/w3c/resource-hints/issues/7... underspecified and I'm planning to add a section to address this. 

That said, do we really need a "default" keyword? The spec states that "inert" is default if not specified, and if you want, you can spell it out in your markup as well.

**Comment by toddreifsteck** [comment]
I read the current definition of loadPolicy as having a default of "may preprocess" and that "inert" is a specific change from the default loadPolicy. Did I misinterpret your intent?

**Comment by igrigorik** [comment]
`<facepalm />` no, you're right absolutely right...

Perhaps adding `opportunistic` as default strategy would do the trick? Personally I'd prefer it to be more descriptive than "default".

**Comment by toddreifsteck** [comment]
100% agree on a descriptive noun. opportunistic is a bit long. I’ll think on it a bit.

**Comment by igrigorik** [comment]
Closing, will be addressed by #17.
