### ISSUE TITLE
Mixed content policy

### ISSUE THREAD

**Issue by yoavweiss** [w3c/preload#50]
We should decide what should be the mixed content behavior of preload based resources.
Can we simply block all of them? Should they behave the same way that their equivalent typed resources do?

/cc @mikewest

**Comment by igrigorik** [comment]
> Should they behave the same way that their equivalent typed resources do?

This makes sense to me.

**Comment by igrigorik** [comment]
Assuming it's the equivalent case, is there anything actionable for the spec here? We already mention in the privacy and security section that authors should specify relevant mixed-content rules.

**Comment by yoavweiss** [comment]
If I read [the spec](https://w3c.github.io/webappsec-mixed-content/#category-optionally-blockable) correctly, `<link rel=preload>` based resources will be "blockable content" regardless of type. I'm not sure that's a bad thing (e.g. images loaded via `srcset` are "blockable", because they're a "new thing" with no legacy baggage).

**Comment by mikewest** [comment]
I would prefer to not carve anything out for preloaded resources. That is, I'm perfectly happy for secure pages with insecure preload requests to be slower than pages with secure preload requests. That seems like it's WAI.

**Comment by mikewest** [comment]
As Yoav notes, the spec bases its decisions entirely upon the flags y'all send into Fetch. https://w3c.github.io/webappsec-mixed-content/#should-block-fetch should give you the detail about what those flags would mean once run through the MIX algorithm.

**Comment by igrigorik** [comment]
Makes sense to me. We call fetch, which runs the above algorithm as a substep. 

With that in mind, is there anything spec-actionable on this end? To me, the whole point of leveraging fetch is to get these behaviors "for free", without having to enumerate each and every one explicitly.

**Comment by yoavweiss** [comment]
Fair enough. No spec changes needed (here or elsewhere). Closing.
