### ISSUE TITLE
Defining "destination"

### ISSUE THREAD

**Issue by yoavweiss** [w3c/preload#51]
While [applying the connect-src directive to empty type preloads](https://codereview.chromium.org/1632523002/) it came up that CSP changes would be required unless we make sure that the "destination" of such empty type preloads is a "subresource".

I think we can easily change it here, and avoid special-casing it in CSP.

Thoughts?

/cc @igrigorik @mikewest @annevk

**Comment by igrigorik** [comment]
I think this is part of https://github.com/w3c/preload/issues/37. Can we merge this bug into it?

**Comment by yoavweiss** [comment]
Fair enough. I'll close here and add a comment there.
