### ISSUE TITLE
JSON files and preload

### ISSUE THREAD

**Issue by ghost** [w3c/preload#62]
Hello,

What is the correct code for JSON files to preload them or we can not preload JSON files. (just adding them to service worker right now and thinking to add them to my preload list as well, but can't seem to find the correct 'as' code to use).

p.s. I am talking about something like: manifest.json

Thanks.

**Comment by igrigorik** [comment]
The question is how you're going to consume the preloaded response.. Practically speaking, I'm assuming it'll be an XHR and/or fetch() call, which means you can leave `as` empty.

**Comment by ghost** [comment]
lovely thanks for quick response (as always)
