### ISSUE TITLE
as=video & as=audio examples should be as=media

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/preload#64]
http://w3c.github.io/preload/#attributes has examples with `<link rel=preload as=audio href=...>` and `<link rel=preload as=video href=...>` but per the [Fetch spec `video` and `audio` are not valid request destinations](https://fetch.spec.whatwg.org/#concept-request-destination). Instead they are [request types](https://fetch.spec.whatwg.org/#concept-request-type) that correspond to the `media` request destination.

**Comment by igrigorik** [comment]
Good catch, thanks for reporting this.
