### ISSUE TITLE
"Keyword" -> "Link Relation Type"

### ISSUE THREAD

**Issue by dret** [w3c/preload#65]
there are many places where the draft talks about the "keyword", whereas technically speaking it should be a "link relation type" or maybe shorter just "link relation" or "relation type". before making a PR (because there are quite a number of changes): would you consider switching terminology?

**Comment by igrigorik** [comment]
> To determine which link types apply to a link, a, or area element, the element's rel attribute must be split on spaces. The resulting tokens are the keywords for the link types that apply to that element. [source](https://html.spec.whatwg.org/#linkTypes)
> ...
> The prefetch keyword may be used with link, a, and area elements. This keyword creates an external resource link. 

I think keyword is correct in this context. Keyword is what we get by splitting the content of `rel` attribute, and keyword is what then establishes the link relation type.

**Comment by dret** [comment]
fair enough. i may be too much of a "use the less generic term whenever possible" kind of guy.

**Comment by plehegar** [comment]
interestingly, I updated the draft charter earlier today and I avoided using the word keyword in the description of the spec because I thought it was too arcane. 
[[
This specification defines the link type preload, a declarative fetch primitive that initiates an early fetch and separates fetching from resource execution.
]]

**Comment by dret** [comment]
On 2016-05-09 11:24, Philippe Le Hegaret wrote:

> interestingly, I updated the draft charter earlier today and I avoided
> using the word keyword in the description of the spec because I thought
> it was too arcane.
> [[
> This specification defines the link type preload, a declarative fetch
> primitive that initiates an early fetch and separates fetching from
> resource execution.
> ]]

maybe use the term "link relation type" instead, which is the 
terminology used by the relevant spec.

https://tools.ietf.org/html/rfc5988#section-4.1
