### ISSUE TITLE
Load event scheduling

### ISSUE THREAD

**Issue by yoavweiss** [w3c/preload#69]
Currently it's not well defined what should happen with `load` event of preloaded resources that are later also fetched by other nodes (think `<link href="foo.jpg" rel=preload as=image onload>` and `<img src="foo.jpg" onload>`).
- Should the resource download block the document's load event? (IMO, it should)
- Should the resource's load event fire before the document's load event? (IMO, it should)
- Should the `<link>` load event fire before `<img>`'s? (No strong opinion, but firing in discovery order probably makes sense)

/cc @zcorpan

**Comment by igrigorik** [comment]
**Should the resource download block the document's load event? (IMO, it should)**

In 2.1, under _obtain the preload resource_ we state: 
> The preload link element must not delay the load event of the element's node document.

**Should the resource's load event fire before the document's load event? (IMO, it should)**

Per above, no, not necessarily. If it happens to complete before document's load event.. yes. Alternatively, if you have a preload, but then also initiate a load-blocking request then that request will push out the document load event until preload has finished and the load-blocking response is satisfied.

**Should the <link> load event fire before <img>'s? (No strong opinion, but firing in discovery order probably makes sense)**

This seems like an HTML spec question. If I have two image tags, both requesting the same resource, are the load events guaranteed to fire in doc-discovery order? I don't think there is anything preload specific here.

**Comment by yoavweiss** [comment]
> In 2.1, under obtain the preload resource we state:
> 
> The preload link element must not delay the load event of the element's node document.

Yeah, but I'm talking specifically about a case in which that resource is discovered and also fetched by another node. It makes little sense to have e.g. an image download not block the document's load event only because it was also preloaded.

 


> Per above, no, not necessarily. If it happens to complete before document's load event.. yes. Alternatively, if you have a preload, but then also initiate a load-blocking request then that request will push out the document load event until preload has finished and the load-blocking response is satisfied.

Yeah, but it's not a separate request. It's a single resource discovered by two different nodes. (which I believe is under-defined today both here and elsewhere)


> This seems like an HTML spec question. If I have two image tags, both requesting the same resource, are the load events guaranteed to fire in doc-discovery order? I don't think there is anything preload specific here.

Fair enough

**Comment by igrigorik** [comment]
> The preload link element must not delay the load event of the element's node document.
>> Yeah, but I'm talking specifically about a case in which that resource is discovered and also fetched by another node. It makes little sense to have e.g. an image download not block the document's load event only because it was also preloaded

That's not what I was suggesting. My point is: preload-initiated resources should _never_ block onload. However, if the same resource is also requested by another element that _does_ block onload, then said resource will implicitly push out the onload event until preload has finished and it is able to get the response. As such, preload's load event will fire before the document onload, but only because there is another resource that is forcing this behavior. This behavior already falls out of the current definitions, I don't believe we need to do anything else here.

**Comment by yoavweiss** [comment]
OK, sounds like we agree on desired behavior, and I think you're right that this falls from current definitions. Closing
