### ISSUE TITLE
Small styling bug in second example in Introduction

### ISSUE THREAD

**Issue by Lennie** [w3c/preload#70]
In the second example in the Introduction, I see this:
Link: <https://example.com/other/styles.css&gt;; rel=preload; as=style

Obviously &gt; should be >

See:

https://www.w3.org/TR/preload/#introduction

Probably a mistake was made on line 114 of the current version:

https://github.com/w3c/preload/blob/gh-pages/index.html#L114

**Comment by yoavweiss** [comment]
This is working fine in the [editor's draft](http://w3c.github.io/preload/), so maybe it's a bug in the older version of respec?

/cc @marcoscaceres

**Comment by marcoscaceres** [comment]
having a look
