### ISSUE TITLE
type-attribute description is unclear

### ISSUE THREAD

**Issue by Munter** [w3c/preload#73]
The document contains examples of the `type`-attribute, but only for fonts with the `font/woff2` type. For which request destinations is the `type`-attribute recommended or required?

**Comment by igrigorik** [comment]
`type` is there to hint the browser to download this font _if_ it supports the particular mime-type (in the example, that would be `woff2` format). You should use it for content-types that don't have uniform support across all the browsers.

**Comment by Munter** [comment]
So I guess fonts and images. The rest seems pretty stable at the moment. I'll adapt my assetgraph modelling to fit with this: https://github.com/assetgraph/assetgraph/blob/master/lib/relations/HtmlPreloadLink.js
