### ISSUE TITLE
Need clarification for iframe preload

### ISSUE THREAD

**Issue by gopalmor** [w3c/preload#74]
Thanks for bringing up these specs. I think there is conflict in specs for iframe. 

To be specific, Section 2.2 says 

`<iframe>, <frame>  <link rel=preload as=document href=...>
`

whereas Example 7 says

`<link rel="preload" href="//example.com/widget.html" as="iframe">
`

Could you please clarify which one is correct/recommended usage for preloading iframes? as="document" or as="iframe" ?

Thanks

**Comment by yoavweiss** [comment]
Thanks for reporting! :) It should be `as=document`.
Just a note regarding implementations: `as=document` is not currently supported in Blink. See [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=593267) for full discussion.

**Comment by gopalmor** [comment]
Thank you for the clarification and pointer to [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=593267) on as=document support in Blink.
