### ISSUE TITLE
Transition Level 1 to CR

### ISSUE THREAD

**Issue by igrigorik** [w3c/preload#76]
- **Known / outstanding spec issues**
  - [ ] https://github.com/w3c/preload/milestone/1
- **Web platform tests**
  - [x] [upstream Blink tests](https://github.com/w3c/web-platform-tests/tree/master/preload)
- **Privacy and security**
  - [x] http://w3c.github.io/preload/#privacy
- **Implementations**
  - [x] Chrome: [M50+](https://www.chromestatus.com/feature/5757468554559488)
  - [x] Firefox: [M56](https://bugzilla.mozilla.org/show_bug.cgi?id=1222633)
  - [ ] Edge: [under consideration](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/preload/)
  - [x] Safari: https://bugs.webkit.org/show_bug.cgi?id=158720
- **Public signals: adoption, feedback...**
  - https://www.chromestatus.com/metrics/feature/timeline/popularity/1124

**Comment by igrigorik** [comment]
@yoavweiss any chance you could help with the web-platform-tests for this one? Also, any pointers for Safari discussions/bugs we can link to?

**Comment by yoavweiss** [comment]
@igrigorik - on my TODO list. If I'm realistic, it probably won't happen before Velocity AMS, but I'll carve out the time to get it done not long after.

Master WebKit issue is https://bugs.webkit.org/show_bug.cgi?id=158720

**Comment by igrigorik** [comment]
@yoavweiss sounds great, thanks!

**Comment by toddreifsteck** [comment]
I know it is already in progress but I want to ensure that we are clear that the tests are super critical for this spec given its "background" nature. I assert that we MUST get tests into Web Platform Tests before moving this to the next phase.

**Comment by yoavweiss** [comment]
Later than I thought, but first batch of tests is at https://github.com/w3c/web-platform-tests/pull/4316

**Comment by yoavweiss** [comment]
@toddreifsteck @igrigorik - I'd appreciate your review of the tests and mostly a list of scenarios which are not currently covered.

**Comment by addyosmani** [comment]
w3c/web-platform-tests#4316 (which was great to see land) noted that this was an incomplete set of tests. @yoavweiss do you know if there are additional tests that need to be landed beyond https://github.com/w3c/preload/issues/92?

**Comment by siusin** [comment]
@yoavweiss @igrigorik 
do you think this spec needs a [TAG review](https://github.com/w3ctag/design-reviews)?  I know a few TAG members are involved in the design of this spec, but can't find the record of a formal review.

**Comment by toddreifsteck** [comment]
@siusin @yoavweiss @igrigorik I believe a TAG review is supposed to be part of every new spec's publishing process. We should get this spec on the list, but I don't believe that needs to block the request to publish.

**Comment by yoavweiss** [comment]
With 2.5 shipping implementations and presence in [0.9% of page views](https://www.chromestatus.com/metrics/feature/timeline/popularity/901), I think it's a bit late for that :/ While we can go through the motions, I don't think we'd be able to act on any recommendations that'd result in breaking changes.

**Comment by siusin** [comment]
I'd suggest we at least formally ask the TAG if they wish to review this, also the Web Plat WG. It won't take long...

**Comment by igrigorik** [comment]
Hmm, I'm surprised we missed the formal TAG bit here -- I'll take the blame for that, should have caught it earlier! Pinging TAG for formal review sgtm, with an explicit note that this has already shipped and has a good ramp on adoption. Yoav, would you be willing to drive that?

**Comment by siusin** [comment]
[Draft] Call for Review --

## TAG Review:

#### I'm requesting a TAG review of:

  - Name: Preload
  - Specification URL: https://www.w3.org/TR/preload/
  - Explainer, Requirements Doc, or Example code: https://www.w3.org/TR/preload/#introduction
  - Tests: https://w3c-test.org/preload/
  - Primary contacts: @igrigorik @yoavweiss 
  - Relevant time constraints or deadlines: N/A

#### Further details (optional):
- [x] I have read and filled out the [Self-Review Questionnare on Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/) ([details](https://github.com/w3c/preload/issues/76#issuecomment-331933543)).
- [x] I have reviewed the TAG's [API Design Principles](https://w3ctag.github.io/design-principles/)

#### You should also know that...

The Preload spec has already got [2.5 shipping implementations](http://caniuse.com/#feat=link-rel-preload) and presence in [0.9% of page views](https://www.chromestatus.com/metrics/feature/timeline/popularity/901).

#### We'd prefer the TAG provide feedback as (please select one):
- [x] open a single issue in our Github repo for the entire review

### Self-Review Questionnare on Security and Privacy:
  - Does this specification deal with personally-identifiable information?
No.
  - Does this specification deal with high-value data?
No.
  - Does this specification introduce new state for an origin that persists across browsing sessions?
No.
  - Does this specification expose persistent, cross-origin state to the web?
No.
  - Does this specification expose any other data to an origin that it doesn’t currently have access to?
No.
  - Does this specification enable new script execution/loading mechanisms?
Yes.
This specification defines the preload keyword that may be used with link elements, it provides a declarative fetch primitive that initiates an early fetch and separates fetching from resource execution.
  - Does this specification allow an origin access to a user’s location?
No.
  - Does this specification allow an origin access to sensors on a user’s device?
No.
  - Does this specification allow an origin access to aspects of a user’s local computing environment?
No.
  - Does this specification allow an origin access to other devices?
No.
  - Does this specification allow an origin some measure of control over a user agent’s native UI?
No.
  - Does this specification expose temporary identifiers to the web?
No.
  - Does this specification distinguish between behavior in first-party and third-party contexts?
No.
  - How should this specification work in the context of a user agent’s "incognito" mode?
The feature would work in such a way that the website would not be able to determine that the user was in "incognito".
  - Does this specification persist data to a user’s local device?
No.
  -  Does this specification have a "Security Considerations" and "Privacy Considerations" section?
Yes.
https://w3c.github.io/preload/#privacy.
  - Does this specification allow downgrading default security characteristics?
Yes.
Preload links for CORS enabled resources, such as fonts or images with a crossorigin attribute, must also include a crossorigin attribute, in order for the resource to be properly used.

@igrigorik @yoavweiss could you give a quick check of the above review details before we send out the wide review requests?

**Comment by igrigorik** [comment]
@siusin thanks for drafting this! GH formatting was broken in a few places --> updated. LGTM.

**Comment by Krinkle** [comment]
@siusin For what it's worth, it seems two of the test suites fail over HTTP (in Chrome at least). Might want to link w3c-test.org over HTTPS instead.

**Comment by siusin** [comment]
Done.

Thanks @Krinkle !

**Comment by yoavweiss** [comment]
Opened a TAG review request at https://github.com/w3ctag/design-reviews/issues/202

**Comment by siusin** [comment]
CR Published on [26-Oct](https://www.w3.org/TR/2017/CR-preload-20171026/).

Thanks all for getting this done.

**Comment by yoavweiss** [comment]
@siusin Thank you for publishing! :)

**Comment by igrigorik** [comment]
Yay! Thanks all.
