### ISSUE TITLE
Require "as" attribute

### ISSUE THREAD

**Issue by AshleyScirra** [w3c/preload#80]
Based on discussion from this report: https://bugs.chromium.org/p/chromium/issues/detail?id=655698

Allowing a normal fetch preload with an accidentally missing "as" attribute is a gotcha. For example if you preload a script with a missing "as", then later add an actual script referencing it, apparently the current specified behavior is:

1. Fetch the resource over the network as per the preload directive.
2. Script is added to the document: fetch the resource over the network a second time.
3. Use the second copy. First copy is ignored.

This is obviously a significant deoptimisation compared to not using the preload at all!

Therefore I would suggest the "as" attribute should be required. If the developer intends to do a fetch type preload, I suggest explicitly opting in to it with `as="fetch"`, and logging an error if the "as" attribute is missing. This should make identifying mistakes more straightforward.

**Comment by igrigorik** [comment]
We define preload as "declarative fetch". As such, by default it behaves just like any other `fetch()`'ed resource. If you omit `as`, the default value is the empty string, which maps to [the corresponding destination in Fetch](https://fetch.spec.whatwg.org/#concept-request-destination).

- Treating explicit `as=""` differently from the missing value would be rather weird in my books.
- I don't believe missing `as` is any more of a gotcha than, say, missing `media` value, which can similarly have big implications for your application if wrong stylesheet is applied.

My preference is to keep it optional. We don't force mandatory attributes on other relations / attributes.

**Comment by AshleyScirra** [comment]
I think the feature should be designed so that using it wrong isn't worse than not using it at all. Maybe there's some other way the worst-case behavior can be avoided?

**Comment by igrigorik** [comment]
> I think the feature should be designed so that using it wrong isn't worse than not using it at all.

At the limit, that would require that any preload-initiated fetch could be re-used by any other fetch, but that's simply not possible due to various security restrictions in place. We can't eliminate the 'worst case' here.

That said, I think your main concern is with the default value / absence of `as`: if the developer is not aware of `as` or forgot it, then they might be surprised to see double fetches for some resources... but that's where DevTools can help - e.g. highlight fetched but never used resources (not limited to preload either btw), optionally log a warning if as is missing, etc.

**Comment by simevidas** [comment]
When omitting the `as` attribute on my website and then inspecting the requests in the Chrome DevTools Network panel, I’m seeing double downloads for `script`, `style`, `image`, and `font` cases. 

@igrigorik Could you provide a use case or an example of a scenario where the `as` attribute is omitted. I would like to understand how `rel=preload` can be used without the `as` attribute, in practice. The only example I could find in the spec, is:

```html
<link rel="preload" href="//example.com/resource">
```

which is described as “an unknown resource type from another origin” that “is equivalent to a fetch initiated `XMLHttpRequest` request”. So, if I understand correctly, the only way to “use” this preloaded resource later without causing a double download would be to fetch it via the XHR or Fetch APIs.

**Comment by igrigorik** [comment]
@simevidas `as` value sets the [request destination](https://fetch.spec.whatwg.org/) defined by Fetch API. An empty `as` maps to empty `destination` value, which in turn is any request subject to `connect-src` CSP policy -- e.g. navigator.sendBeacon(), EventSource, HTML’s ping="", fetch(), XMLHttpRequest, WebSocket.

Does that help?

**Comment by yoavweiss** [comment]
A practical note: currently in Chromium, fetch() and non-credentialed XHR are not being reused. See https://crbug.com/652228 for more details.

**Comment by yoavweiss** [comment]
I think we have two options here:

1) Current route, in which a missing `as` value is considered an empty Fetch destination, and therefore can only be reused by requests that are subject to `connect-src`. In this case, we rely on dev tools warnings to notify developers when the resource they preloaded was not reused, and they incurred a double download on their users.
2) Alternatively, we could map a `connect` (or whatever) keyword in `as` to be the Fetch empty destination, and when `as` is missing, no preload is triggered. If we're seeing a lot of developers breaking their teeth on an empty `as`, that might be the more user-friendly approach, because when you get things wrong, you get no optimization, which is better than de-optimization.

For route 2, we could also try to add a non-empty Fetch destination to the Fetch spec, which would alias the empty destination, and only allow that non-empty one in preload. @annevk - thoughts on that?

**Comment by MarcoHengstenberg** [comment]
Imho the second option is the way to go.

As there's no point in actively dismissing the `as` attribute in the first place, not impacting the user with an error made in development is always a good decision.

Just my 2 cents. =)

**Comment by AshleyScirra** [comment]
Second option is what I suggested originally - IMO something like `as="fetch"` is clearer and less error prone. This is the principle of "explicit is better than implicit".

**Comment by annevk** [comment]
@yoavweiss why wouldn't you make omitting `as` simply default to no fetching whatsoever? I.e., only when you specify the attribute would `rel=preload` processing continue.

**Comment by annevk** [comment]
Oh, @igrigorik argued against that, but I somewhat disagree that "empty as" and "omitted as" are identical. (They can be, but if the empty string value results in surprise it seems better to treat them different.)

**Comment by yoavweiss** [comment]
I suspect that different behavior for omitted `as` vs. empty `as` will be confusing for most users.

**Comment by annevk** [comment]
Why? That's how `<a>` works for `href` or `<script>` for `src`.

**Comment by yoavweiss** [comment]
True, but:

* That's also confusing, and for many years browsers with e.g. `<img src>` where [re-downloading](https://www.nczonline.net/blog/2009/11/30/empty-image-src-can-destroy-your-site/) the HTML for the image resource, which makes little sense and wasted a lot of bandwidth. I vaguely remember this as fixed by at least some browsers, but in any case, we can avoid repeating past mistakes.
* An empty `as` value doesn't "tell" developers what it would do. I totally agree that for `fetch()` a default destination makes sense, but for `as` it's pretty cryptic.

**Comment by mems** [comment]
@simevidas I've got a case when a webapp need to require a large JSON (or require server side heavy computations) and load it when the JS/app is ready (loaded by `fetch()` or `XMLHttpRequest`)

**Comment by zcorpan** [comment]
How about:

* omitted or empty is non-conforming (conformance checkers will give an error message)
* omitted or empty makes the preload keyword synonym for preconnect or dns-prefetch, or ignore.

**Comment by yoavweiss** [comment]
> How about:
> 
> omitted or empty is non-conforming (conformance checkers will give an error message)
> omitted or empty makes the preload keyword synonym for preconnect or dns-prefetch, or ignore.

Interesting! (and we could do the same with invalid `as` values that are currently dropped).

At the same time, that doesn't absolve us from figuring out plumbing to enable some `as` value that would map to `connect-src` constrained resources.

**Comment by zcorpan** [comment]
as="fetch" ?

**Comment by yoavweiss** [comment]
sure. That would require either:
* Adding "fetch" as an alias to the empty destination in Fetch.
* Adding "fetch" as an alias to the empty destination as part of preload.

**Comment by zcorpan** [comment]
Or have the HTML spec map it to the empty string destination.

**Comment by zcorpan** [comment]
cc @sideshowbarker

**Comment by sideshowbarker** [comment]
from https://github.com/w3c/preload/issues/80#issuecomment-267782617

> omitted or empty is non-conforming (conformance checkers will give an error message)

Makes sense to me and would be happy to implement that in the HTML checker

**Comment by zcorpan** [comment]
Thinking about this a bit more, I think this option is least surprising/least weird:

> Adding "fetch" as an alias to the empty destination in Fetch.

That is, it should be possible to take the value from the `as` attribute and pass it in to `fetch()` directly.

**Comment by zcorpan** [comment]
I guess the `Link` HTTP header should have the same requirements and behavior?

**Comment by yoavweiss** [comment]
yeah

**Comment by igrigorik** [comment]
To recap, the proposal is: 

* **Treat omitted or empty `as` as non-conforming**
  - No fetch is triggered
  - DevTools / conformance checkers will return an error message
  - Optionally, UA's can treat it as a preconnect? Although, if the browser doesn't understand the destination, there is also a good chance it doesn't need the response. As such, I suggest we punt on this for now.
* **Map `fetch` attribute value to empty destination for Fetch**
  - We can add this step in Preload spec, as a processing step for `as` attribute value.
* **Same conditions apply to Link header.**

Does that capture it? @annevk does that sound reasonable to you?

**Comment by AshleyScirra** [comment]
Looks good to me.

**Comment by annevk** [comment]
I think if we add a new value we should maybe add it to Fetch or at least ensure somehow Fetch can never mint it.

**Comment by igrigorik** [comment]
@annevk is it worth considering changing the default empty value to instead be "fetch", or some such? That'd have ripple effects on other parts of Fetch spec.. but it would remove the need for any magic aliases.

**Comment by annevk** [comment]
It is, but then we get into web-compatible territory.

**Comment by yoavweiss** [comment]
This is currently blocked on https://github.com/whatwg/fetch/pull/442

**Comment by yoavweiss** [comment]
No longer blocked on https://github.com/whatwg/fetch/pull/442 but on https://github.com/whatwg/fetch/pull/547

**Comment by igrigorik** [comment]
@yoavweiss https://github.com/whatwg/fetch/pull/547 landed. What remains here?

**Comment by yoavweiss** [comment]
https://github.com/whatwg/fetch/pull/549 (which I missed in the previous PR).
Also, https://github.com/whatwg/html/pull/2588 is unifying the processing model with the rest of the link elements, and https://github.com/yoavweiss/html/commit/ed99510d897c7dafacce537d177ee4b1cfc7b90d adds the required "potential destination" calls to it.

Once all those land, we can close this, and remove the preload-specific processing model.

**Comment by yoavweiss** [comment]
Closed by https://github.com/whatwg/html/pull/2588 and https://github.com/whatwg/fetch/pull/549

**Comment by yutakahirano** [comment]
Several examples in https://w3c.github.io/preload/ contain link preloads without "as" attribute. They should be fixed, right?

**Comment by yoavweiss** [comment]
@yutakahirano Indeed. PR at https://github.com/w3c/preload/pull/98
