### ISSUE TITLE
Define resource abortion when link element or `rel` are removed 

### ISSUE THREAD

**Issue by yoavweiss** [w3c/preload#82]
As pointed out in the review of https://github.com/w3c/web-platform-tests/pull/4316, currently there's no tight definition of what the UA should do:
* When the preload link's link element is removed from a document.
* When the preload link is changed or removed on a link element that is already in a Document.

IMO it makes sense for the UA to abort the request if it's in flight (similar to "The user agent should abort the current request if the href attribute of the link element of a preload link is changed, removed, or its value is set to an empty string.")

If that makes sense, I'll PR something to that effect.

**Comment by igrigorik** [comment]
That seems like an HTML spec issue, no? What happens to both of the above when applied a stylesheet?

**Comment by yoavweiss** [comment]
Currently the "appropriate time to obtain a resource" is defined here for preload as well as in HTML, specifically for [link type stylesheet](https://html.spec.whatwg.org/#link-type-stylesheet). If we want to keep current structure, we'd need to define it here, and potentially also in HTML.

FWIW, terminating the download when `href` is changed or removed (which is defined here) seems to make sense for stylesheets as well.

**Comment by igrigorik** [comment]
Could we take this up on HTML spec first, and see if we have agreement there? Then, assuming the answer is "yes", propagate it down to Preload?

**Comment by yoavweiss** [comment]
Sure. I'll open an issue there

**Comment by igrigorik** [comment]
@yoavweiss did we open an issue on HTML spec? Anything actionable for this spec here?

**Comment by yoavweiss** [comment]
Submitted https://github.com/whatwg/html/issues/2931
No further action here as the processing model is now part of HTML.
