### ISSUE TITLE
Priority and loading order issues with link preloads

### ISSUE THREAD

**Issue by pelchats** [w3c/preload#84]
There's a feature gap between the `Link: rel=preload` header compared to the `link` HTML element, since in the latter case, the browser can use the position of the link attribute to determine the prioritization of the request. In the former case, the only information the browser has is the resource type. It would be nice to address (or at least mention) that gap in the spec.

**Comment by yoavweiss** [comment]
As discussed at the loading summit, I believe this should be resolved by [way to indicate resource priority](https://docs.google.com/document/d/1qS_STvvMml_5oNxp_VZgqdeeZE448t4UTIfiMQvibbk/edit), which shouldn't necessarily be specific to preload.

**Comment by pelchats** [comment]
I filed this issue because I didn't think there was any plan on specifying a way (and that there wasn't much interest in doing so) to indicate resource priority. I agree your suggestion is the proper way to resolve this issue. Feel free to close if there is sufficient traction in your proposal.

**Comment by yoavweiss** [comment]
Action here is to add a mechanism informing the browser on a resource's priority/deferability.

I need to do some more research to convince myself of the required mechanism's functionality, but seems like for L1, we'd want a way to make sure future-compatibility and decide on the keyword that would be used in that future mechanism, so that L1 compliant implementations can reserve them, and ignore `preload` in their presence. I'm adding an L1 milestone for that reason.

**Comment by igrigorik** [comment]
> As discussed at the loading summit, I believe this should be resolved by way to indicate resource priority, which shouldn't necessarily be specific to preload.

^ +1 to that. It's not that there wasn't much interest, as much as.. nobody was willing to put in the time to actually define it as a browser primitive. It's easy to bolt on an ad-hoc solution to a particular feature; it's much harder to figure out all the platform requirements to make it coherent across the board.

I propose we focus on the platform-wide story:
- start a WICG thread / repo dedicated to effort
- migrate this discussion there

I don't think specifying preload specific keywords is the right long-term solution.

**Comment by igrigorik** [comment]
@pelchats based on the 👍 , it sounds like you're on board.. :) Can you take the AI to start the new WICG discussion? Closing this thread, as what we're looking for here is not preload specific.

**Comment by pelchats** [comment]
SGTM. It will take me some time to think of sensible proposal, but I'll create WICG thread when I have some concrete ideas. Thanks!

**Comment by alcidesv** [comment]
Let me see if I get this: at the server side, we write a link header where we indicate resource priority. The server sends this header to the browser, and the browser then tells the server "give me this resource with this priority" ... why would we send the priority information to the browser on first place?

**Comment by yoavweiss** [comment]
@alcidesv
1) The server may not be the same server. Giving priority info to the browser would enable it to manage priorities between the origin and third party servers.
2) The browser may delay issuing of low-priority requests while higher priority ones are pending for multiple reasons. Telling the browser the resource's priority would enable it to do that.
