### ISSUE TITLE
Fire 'error' event if URL fails to parse

### ISSUE THREAD

**Issue by zcorpan** [w3c/preload#88]
https://w3c.github.io/preload/#dfn-obtain-the-preload-resource

> If the previous step fails, then abort these steps.

I expected this to fire an `error` event. Any reason not to?

**Comment by annevk** [comment]
Do we do that for `<link rel=stylesheet>`?

**Comment by zcorpan** [comment]
Seems not. Maybe we should?

These do not fire `error`
`link`, `track`, `iframe` (never fires `error` I think), `embed`, `input type=image`, `menuitem icon` (fine), `video poster` (fine) 

These do:
`img`, `script`, `object`, `audio`/`video`

**Comment by yoavweiss** [comment]
It makes sense to me to fire an error event in this case, probably for all `<link>`s

**Comment by yoavweiss** [comment]
Now that the processing model is moving to HTML and gets merged into link element's one, I think this issue should be opened against the HTML spec
