### ISSUE TITLE
matching request before load?

### ISSUE THREAD

**Issue by getify** [w3c/preload#9]
What happens if I make a "matching request" (for whatever that means) while the preloading is still happening? Does the main request just sit subordinately and wait?

Does it pay a cache hit performance wise? IOW, is it like appcache, where a request if the resource isn't preloaded would just try to load from a cached version?

**Comment by igrigorik** [comment]
The matching request would be "deduped" by the net stack and request would block on the preload request; just as it does today when you have multiple parallel requests against the same resource.

No, not like appcache: the request is subject to all the same cache headers; if a previously fetched response is stale it would be revalidated.. Think XHR, but declarative.
